# Generated by Django 2.2.6 on 2020-05-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('reg', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_number', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('b_group', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Signup_User')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('qualification', models.CharField(max_length=30, null=True)),
                ('specialist', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Signup_User')),
            ],
        ),
    ]
