# Generated by Django 2.2.6 on 2020-05-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.TimeField(null=True)),
                ('date1', models.DateField(null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Doctor')),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Patient')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Status')),
            ],
        ),
    ]
