# Generated by Django 2.2.6 on 2020-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
