# Generated by Django 2.2.6 on 2020-05-24 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_auto_20200525_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100, null=True)),
                ('prescription', models.TextField(null=True)),
                ('date1', models.DateField(null=True)),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Doctor')),
                ('pat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hopital.Patient')),
            ],
        ),
    ]
