# Generated by Django 2.2.6 on 2020-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0007_auto_20200525_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_date',
            field=models.DateField(null=True),
        ),
    ]
