# Generated by Django 2.2.6 on 2020-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0008_doctor_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='salary',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
